# JDBC \u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.pcc.demo.entity
  mapper-locations: classpath:mapper/**/*.xml
  check-config-location: true